# Generated by Django 3.2.6 on 2021-09-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_type',
        ),
    ]
