# Generated by Django 3.2.6 on 2021-09-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_seat_seat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_type',
        ),
    ]
