# Generated by Django 3.2.6 on 2021-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paid_by',
        ),
        migrations.AddField(
            model_name='seat',
            name='booked',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BookedSeat',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
