# Generated by Django 3.2.6 on 2021-09-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210930_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='no',
        ),
    ]
