# Generated by Django 3.2.6 on 2021-09-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_seat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
