# Generated by Django 3.2.6 on 2021-08-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='certificate',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG13', 'PG13'), ('NC16', 'NC16'), ('M18', 'M18'), ('R21', 'R21')], max_length=4),
        ),
    ]
