# Generated by Django 3.2.6 on 2021-09-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
